Feat/dmv
theunitedeffort/theunitedeffort.org pull request #293
Opened 2023-03-04 21:26 UTC by rajivrajiv

Implemented reducedFeeIdEligible().

2023-03-04 23:09 UTC, trevorshannon requested changes
Thanks very much!  The main request here is to remove IHSS and WIC from the list of programs that makes a person eligible for a reduced-fee ID.  Let me know if you disagree with that interpretation.

2023-03-04 23:09 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +    //   so could be part of the broader WIC benefits progam.
The "WIC" in this case is the "welfare institutions code" and unassociated with the WIC program.  I believe the program described by WIC §12000 is SSP (the state portion of total SSI payments).

2023-03-04 23:09 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +      document.getElementById("existing-wic-me").checked,
I think this should be removed, as the WIC referenced in the icarol.org and DL 937 documentation is different from the  Women, Infants and Children program.

2023-03-04 23:09 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +      document.getElementById("existing-ihss-me").checked,
I think SSI is the only aged, blind, and disabled program specifically referenced in the DL 937 order form, unless I've missed the reference to IHSS.

2023-03-04 23:09 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +      ihssEligible(),
Likewise, as above.

2023-03-04 23:09 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +      wicEligible(),
Likewise, as above.

2023-03-05 00:04 UTC, rajivrajiv commented
I will remove IHSS and WIC and a couple of comments. 

Why was WIC included in the benefits eligibility spreadsheet based on [ID Cards - California DMV](https://www.dmv.ca.gov/portal/driver-licenses-identification-cards/identification-id-cards/) ?

Thanks

2023-03-05 01:49 UTC, trevorshannon approved these changes
Looks good!

At the time I wrote that benefits eligibility spreadsheet, I _also_ assumed the "WIC" section referenced was having something to do with Women, Infants, and Children.  Since then, I've learned out about the Welfare Institutions Code.

2023-03-05 02:23 UTC, merged