Update eligibility.liquid
theunitedeffort/theunitedeffort.org pull request #301
Opened 2023-03-07 20:34 UTC by rajivrajiv

Implemented liheapEligible() and tested it.

2023-03-08 06:32 UTC, trevorshannon requested changes
Thanks very much!  These comments should be pretty quick to resolve.

2023-03-08 06:32 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +  */
Oops, leftover comment here.

2023-03-08 06:32 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +      7447.56
Should be `7477.56`

2023-03-08 06:32 UTC, trevorshannon commented on src/site/static/eligibility.liquid
> +      7166.00,
Either `.00` like this or `.0` as above in `3531.0` is fine. Can you choose one for consistency?

2023-03-09 04:40 UTC, trevorshannon approved these changes
Looks good!  Feel free to merge whenever convenient.

2023-03-09 14:57 UTC, rajivrajiv commented
Thanks.

2023-03-09 14:58 UTC, merged