Implicit submission
theunitedeffort/theunitedeffort.org pull request #332
Opened 2023-03-27 15:14 UTC by gangaramani-nikhil

2023-03-27 15:16 UTC, gangaramani-nikhil commented
Hi @trevorshannon ,
I have created this pull request for issue #276

2023-03-27 17:55 UTC, trevorshannon requested changes

2023-03-27 19:54 UTC, trevorshannon commented on src/site/_includes/js/eligibility.js
Oh sorry, typo above: `<input>` or `<select>`

2023-03-27 21:28 UTC, gangaramani-nikhil commented
Hi @trevorshannon,
On the first page do you want me to map enter to next button?
There is no input or select element on first page
I am referring to the following page
![image](https://user-images.githubusercontent.com/52930019/228070754-74079ccf-a248-434b-8370-e5e95d4cda3a.png)

2023-03-27 21:33 UTC, gangaramani-nikhil commented on src/site/_includes/js/eligibility.js
> +      document.getElementById("next-button").click();
sure updated in latest commit

2023-03-27 21:38 UTC, gangaramani-nikhil commented on src/site/_includes/js/eligibility.js
solved this issue Thanks

2023-03-27 21:41 UTC, trevorshannon commented
In this case, as there is no input field to have focus, it would not advance when the user presses Enter.

2023-03-27 21:42 UTC, gangaramani-nikhil commented
yep that is how it is implemented now

2023-03-28 02:45 UTC, trevorshannon requested changes

2023-03-28 02:45 UTC, trevorshannon commented on src/site/_includes/js/eligibility.js
> +    if ( event.key === "Enter" && ( document.activeElement.tagName === "INPUT" || document.activeElement.tagName === "SELECT" ) ){
We generally try to follow the Google JS style guide, which recommends omitting spaces just inside the parentheses.

```
if (thisIsGood) {

if ( notRecommended ) {
```

https://google.github.io/styleguide/jsguide.html#formatting-horizontal-whitespace

2023-03-28 02:45 UTC, trevorshannon commented on src/site/_includes/js/eligibility.js
> +  })
Add a semicolon here, please.

2023-03-28 16:11 UTC, gangaramani-nikhil commented
Hi @trevorshannon ,
I have made the changes.

2023-03-28 21:00 UTC, trevorshannon approved these changes

2023-03-28 21:00 UTC, merged